/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StackAndQueue;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

//  @Test
//  void testPushOneNodeToStack() {
//    Stack stack1 = new Stack();
//    stack1.push("1");
//    assertEquals("Stack{\n" +
//      "1\n" +
//      " }", stack1.toString());
//  }

  @Test void canPushToStack(){
    Stack stack = new Stack();
    stack.push("1");
    stack.push("2");
    stack.push("3");
    String expected ="Stack{\n" +
      "3\n" +
      "2\n" +
      "1\n" +
      " }";
    assertEquals(expected, stack.toString());
  }
}
