/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hash;
public class App {


  public static void main(String[] args) {

    String input ="Once upon a time, there was a brave princess who...";
    System.out.println(RepeatedWord.repeatedWord(input));
  }
}

