/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hash;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

      HashTable<String> hashTable = new HashTable<>(10);

      hashTable.add(11,"marah");
      hashTable.add(12,"sara");
      hashTable.add(13,"mais");


      System.out.println(hashTable.get(12));
      System.out.println(hashTable.contains(11));
    }
}
