/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graphs;

import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      System.out.println(new App().getGreeting());

//      Graph graph = new Graph();
//      Vertex vertex = graph.addNode("1");
//      Vertex vertex1 =  graph.addNode("2");
//      Vertex vertex2 = graph.addNode("3");
//      Vertex vertex3 = graph.addNode("4");
//      Vertex vertex4 = graph.addNode("5");
//      Vertex vertex5 = graph.addNode("6");
//      Vertex vertex6 = graph.addNode("7");
//      Vertex vertex7 = graph.addNode("8");
//      Vertex vertex8 = graph.addNode("9");
//      Vertex vertex9 = graph.addNode("10");
//
//
//      graph.addEdge(vertex,vertex1);
//      graph.addEdge(vertex,vertex3);
//      graph.addEdge(vertex1,vertex2);
//      graph.addEdge(vertex1,vertex3);
//      graph.addEdge(vertex2,vertex6);
//      graph.addEdge(vertex3,vertex4);
//      graph.addEdge(vertex3,vertex7);
//      graph.addEdge(vertex3,vertex5);
//      graph.addEdge(vertex7,vertex5);
//      graph.addEdge(vertex7,vertex8);
//      graph.addEdge(vertex8,vertex9);
//      System.out.println(graph.getNeighbors(vertex4));
//      System.out.println(graph.getNeighbors(vertex8));
//
//
//      List<Vertex<String>> MyList = new ArrayList<>();
//      MyList.add(vertex);
//      MyList.add(vertex1);
//      MyList.add(vertex2);
//      MyList.add(vertex3);
//      MyList.add(vertex4);
//      MyList.add(vertex5);
//      MyList.add(vertex6);
//      MyList.add(vertex7);
//      MyList.add(vertex8);
//      MyList.add(vertex9);
//
//      System.out.println(graph.breadthFirstSearch(vertex3));
//      System.out.println(graph.graphBusinessTrip(graph, MyList));

    }
    }

