/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class Library {
  public static void main(String[] args) {
    BinarySearchTree<Integer> binarySearchTree = new BinarySearchTree<>();
    binarySearchTree.add(50);
    binarySearchTree.add(10);
    binarySearchTree.add(60);
    binarySearchTree.add(5);
    binarySearchTree.add(20);
    binarySearchTree.add(55);
    binarySearchTree.add(70);
    System.out.println(binarySearchTree);
//    System.out.println(binarySearchTree.postOrder(binarySearchTree.getRoot()));
//    System.out.println(binarySearchTree.preOrder(binarySearchTree.getRoot()));
    System.out.println(binarySearchTree.inOrder(binarySearchTree.getRoot()));
    System.out.println(binarySearchTree.contains(70));
  }
  }

