/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertionSort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test void insertionSort1() {
    int[] arr = {8, 4, 23, 42, 16, 15};
    int[] expected =  {4, 8, 15, 16, 23, 42};

    assertEquals(Arrays.toString(expected), Arrays.toString(App.insertionSort(arr)));
  }

  @Test void insertionSort2() {
    int[] arr = {4, 13, 8, 4, 6, 8};
    int[] expected =  {4, 4, 6, 8, 8, 13};

    assertEquals(Arrays.toString(expected), Arrays.toString(App.insertionSort(arr)));
  }
  @Test void mergeSort() {
    int[] arr = {8, 4, 23, 42, 16, 15};
    int[] expected =  {4, 8, 15, 16, 23, 42};

    assertEquals(Arrays.toString(expected), Arrays.toString(App.mergeSort(arr)));
  }
    }

